<a href="https://colab.research.google.com/github/princeomarmohamed55/AI-PORTFOLIO-2026/blob/main/NumPyclass_iupynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
numbers =np.array([1,2,3,4,5])

In [ ]:
print(numbers)

[1 2 3 4 5]


list

In [ ]:
marks = [56,67,90,76,80]
print (marks)

[56, 67, 90, 76, 80]


list versus Array 1.lista are flexible,easyto usebut slower for culculations 2. Arrays are faster ,better for culculations ,and are used in ,machine learning and data science

In [ ]:
cat1 =[26,45,24,50,]
cat2=[50,43,30,40]
print(cat1)
print(cat2)
print(cat1+cat2)

[26, 45, 24, 50]
[50, 43, 30, 40]
[26, 45, 24, 50, 50, 43, 30, 40]


In [ ]:
cat1=np.array([34,54,80,90])
cat2=np.array([50,43,30,40])
print (cat1)
print(cat2)
print(cat1+cat2)

[34 54 80 90]
[50 43 30 40]
[ 84  97 110 130]


In [ ]:
zeros= np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [ ]:
ones= np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


using intervals

In [ ]:
even_numbers = np.arange (2,21,2)
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
odd_numbers = np.arange (1,21,2)
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19]


ARRAY INDEXING

In [ ]:
students =np.array(["george", "omar", "nabil","stanely"])
print(students[0])
print(students[-1])

george
stanely


ARRAY SLICING: SLICING MEANS CHOOSING MUTLIPLE ELEMENTS

In [ ]:
print(students[1:3])



['omar' 'nabil']


create the array


In [ ]:
marks =np.array([14,34,56,89,45,35,67,56,54,43])

In [ ]:
print(marks[0])
print(marks[-1])
print(marks[2:5])
print(marks[::2])

14
43
[56 89 45]
[14 56 45 67 54]
