<a href="https://colab.research.google.com/github/princeomarmohamed55/AI-PORTFOLIO-2026/blob/main/NumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
marks = np.array([34,27,35,20,10])
print(np.min(marks))#Minimum mark
print(np.max(marks))#Maximum mark
print(np.mean(marks))#Mean mark
print(np.median(marks))#Median mark
print(np.std(marks))#Standard deviation

10
35
25.2
27.0
9.325234581499814


random numbers

In [6]:
random_scores = np.random.randint(1,100,10)
print(random_scores)
print(np.sort(random_scores))

[64 71  8 12 84 73 84 97 73 54]
[ 8 12 54 64 71 73 73 84 84 97]


reshaping arrays

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8])
reshape_numbers = numbers.reshape(2,4)# reshape(2 rows. 4 columns)
print(reshape_numbers)
print(reshape_numbers[0,1])# accessing elements
print(reshape_numbers[1])# accessing a row
print(reshape_numbers[:,1])# accessing a column

[[1 2 3 4]
 [5 6 7 8]]
2
[5 6 7 8]
[2 6]


Exercise 1: Generate 15 random student scores between 0 and 100, then find the average, highest mark, lowest mark and sort the numbers

In [7]:
random_scores = np.random.randint(1,100,15)
print(random_scores)
print(np.sort(random_scores))
print(np.min(random_scores))
print(np.max(random_scores))
print(np.mean(random_scores))

[44 58 62 93 77 38 62 69 45 34 11 30  1 18 13]
[ 1 11 13 18 30 34 38 44 45 58 62 62 69 77 93]
1
93
43.666666666666664


Excercise 2: Create and array from 1 to 15

In [8]:
array =np.arange(1,16)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Excercise 3: Create 3*4 array representing 3 students and 4 subjects. Then, Find the total marks per student, average marks per student, and highest score on the class

In [ ]:
+